jenkins:
  systemMessage: "Jenkins configured automatically via JCasC"

# Job DSL Section
# Automatically creates Pipeline job from SCM
jobs:
  - script: >
      pipelineJob('ui-automation-ci') {
        description('UI Automation CI - Cross Browser Execution with Parallel Support')

        parameters {
          choiceParam(
            'BROWSER',
            ['CHROME_HEADLESS','FIREFOX_HEADLESS','EDGE_HEADLESS','ALL'],
            'Browser to execute (CHROME_HEADLESS | FIREFOX_HEADLESS | EDGE_HEADLESS | ALL)'
          )

          stringParam(
          'SCENARIO_TAG',
          '@regression',
          'Cucumber scenario tag to execute (e.g. "@TC-00001" or "@regression")'
          )

          stringParam(
          'BASE_URL',
          'https://www.amazon.com',
          'Application base URL (e.g. "https://www.amazon.com")'
          )

          stringParam(
          'EXPLICIT_WAIT',
          '30',
          'Explicit wait timeout in seconds (e.g. "30")'
          )

          stringParam(
          'THREADS',
          '2',
          'Number of parallel threads for test execution (e.g. "2")'
          )
        }
        // Pipeline Definition from Git
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/ovidiocbba/ui-automation-framework')
                }
                branch('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }

# Global Tool Configuration
tool:
  jdk:
    installations:
      - name: "jdk17"
        # Path inside Docker container
        home: "/opt/java/openjdk"

  allure:
    installations:
      - name: "allure"
        # Allure CLI path installed in Docker image
        home: "/usr/bin/allure"
