jenkins:
  systemMessage: "Jenkins configured automatically via JCasC"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_ID}"
          password: "${JENKINS_ADMIN_PASSWORD}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

# Job DSL: Automatically creates the Pipeline job at startup
jobs:
  - script: |
      // Repository configuration
      def JOB_NAME        = 'automation-ci'
      def JOB_DESCRIPTION = 'Automation CI - Cross Browser Execution with Parallel Support'
      def REPO_URL = 'https://github.com/ovidiocbba/ui-automation-framework'
      def REPO_BRANCH = '*/main'
      
      pipelineJob(JOB_NAME) {
        description(JOB_DESCRIPTION)

        // Load Pipeline script from Git (Pipeline as Code)
        definition {
          // cpsScm = CPS (Continuation Passing Style) + SCM (Source Code Management):
          // executes a Pipeline using a Jenkinsfile stored in a Git repository.
          cpsScm {
            // scm = SCM (Source Code Management):
            // defines which repository and branch Jenkins must clone.
            scm {
              git {
                remote {
                  url(REPO_URL)
                }
                branch(REPO_BRANCH)
              }
            }
            // Path to Jenkinsfile inside the repository
            scriptPath('Jenkinsfile')
          }
        }
      }

# Global Tool Configuration
tool:
  jdk:
    installations:
      - name: "jdk17"
        # Path inside Docker container
        home: "/opt/java/openjdk"

  allure:
    installations:
      - name: "allure"
        # Allure CLI path installed in Docker image
        home: "/usr/bin/allure"

# Plugin installation via Configuration as Code (JCasC)
unclassified:
  # Specify the plugins to be installed automatically
    plugins:
      - workflow-aggregator
      - pipeline-stage-view
      - git
      - credentials-binding
      - allure-jenkins-plugin
      - configuration-as-code
      - job-dsl
      - blueocean

# - workflow-aggregator → Enables Pipeline (Jenkinsfile support)
# - pipeline-stage-view → Visual stage view in UI
# - git → Allows Jenkins to clone repositories
# - credentials-binding → Secure usage of secrets in pipelines
# - allure-jenkins-plugin → Integrates Allure test reports
# - configuration-as-code → Allows Jenkins to be configured via YAML files (JCasC),
#   enabling Infrastructure as Code and eliminating manual UI configuration
# - job-dsl → Enables creation of Jenkins jobs via code (Job DSL),
# - blueocean → Provides a modern, user-friendly UI for Jenkins with enhanced pipeline visualization
