jenkins:
  systemMessage: "Jenkins configured automatically via JCasC"

  # Authentication configuration
  # Defines how users log in to Jenkins
  securityRealm:
    local:
      # Disable public user registration
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_ID}"
          password: "${JENKINS_ADMIN_PASSWORD}"

  # Authorization strategy (permissions model)
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      # Prevent anonymous users from accessing Jenkins
      allowAnonymousRead: false

  # Enable CSRF protection (Cross-Site Request Forgery)
  # Stops malicious websites from sending requests to Jenkins using a logged-in user session.
  # excludeClientIPFromCrumb avoids problems when Jenkins runs in Docker or behind a proxy.
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true

# Global Libraries Configuration for Pipeline
unclassified:
  globalLibraries:
    libraries:
      - name: "shared-pipeline-steps"
        defaultVersion: "main"
        allowVersionOverride: true
        includeInChangesets: true
        # The path is set because pipeline libraries (like 'vars/' or 'src/') are inside the 'jenkins/' folder in the repository.
        libraryPath: "jenkins/"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/ovidiocbba/ui-automation-framework"
                traits:
                  - gitBranchDiscovery

# Job DSL: Automatically creates the Pipeline job at startup
jobs:
  - script: |
      // Repository configuration
      def JOB_NAME        = 'automation-ci'
      def JOB_DESCRIPTION = 'Automation CI - Cross Browser Execution with Parallel Support'
      def REPO_URL = 'https://github.com/ovidiocbba/ui-automation-framework'
      def REPO_BRANCH = '*/main'
      
      pipelineJob(JOB_NAME) {
        description(JOB_DESCRIPTION)

        /*
        Parameters are defined here so Jenkins shows "Build with Parameters" immediately.
        Otherwise Jenkins only detects Jenkinsfile parameters after the first build (common with Docker restarts).
        */
        parameters {

          choiceParam(
            'BROWSER',
            ['ALL','CHROME_HEADLESS','FIREFOX_HEADLESS','EDGE_HEADLESS'],
            'Browser to execute (ALL | CHROME_HEADLESS | FIREFOX_HEADLESS | EDGE_HEADLESS)'
          )

          stringParam(
            'SCENARIO_TAG',
            '@regression',
            'Scenario tag to execute (e.g. "@TC-00001")'
          )

          stringParam(
            'BASE_URL',
            'https://www.amazon.com',
            'Base URL (e.g. "https://www.amazon.com")'
          )

          stringParam(
            'EXPLICIT_WAIT',
            '30',
            'Explicit wait timeout in seconds (e.g. "30")'
          )

          stringParam(
            'THREADS',
            '2',
            'Number of parallel threads for test execution (e.g. "2")'
          )
        }

        // Load Pipeline script from Git (Pipeline as Code)
        definition {
          // cpsScm = CPS (Continuation Passing Style) + SCM (Source Code Management):
          // executes a Pipeline using a Jenkinsfile stored in a Git repository.
          cpsScm {
            // scm = SCM (Source Code Management):
            // defines which repository and branch Jenkins must clone.
            scm {
              git {
                remote {
                  url(REPO_URL)
                }
                branch(REPO_BRANCH)
              }
            }
            // Path to Jenkinsfile inside the repository
            scriptPath('Jenkinsfile')
          }
        }
      }

# Global Tool Configuration
tool:
  git:
    installations:
      - name: "Default"
        home: "/usr/bin/git"

  jdk:
    installations:
      - name: "jdk17"
        # Path inside Docker container
        home: "/opt/java/openjdk"

  allure:
    installations:
      - name: "allure"
        # Allure CLI path installed in Docker image
        home: "/usr/bin/allure"
