name: 'Execute features'
description: 'Execute Cucumber features with optional re-run of failed scenarios'

# Inputs the action accepts.
inputs:
  browser:
    description: 'Browser to execute tests (CHROME_HEADLESS | FIREFOX_HEADLESS)'
    required: false
    default: 'CHROME_HEADLESS'

  scenarioTag:
    description: 'Scenario tag to execute (e.g. "@TC-00001")'
    required: true
    default: '@regression'

  baseUrl:
    description: 'Base URL (e.g. "https://www.amazon.com")'
    required: true
    default: 'https://www.amazon.com'

  explicitWait:
    description: 'Explicit wait timeout in seconds (e.g. "30")'
    required: true
    default: '30'

  threads:
    description: 'Number of parallel threads (e.g. "4")'
    required: false
    default: '4'

runs:
  using: 'composite'

  steps:
    - name: Execute Features
      id: execute-features
      # Configuration variables in your repository.
      # Settings -> Secrets and variables -> Actions -> Secrets(secrets) or Variables(vars).
      run: |
        set +e

        echo "================================="
        echo "Executing tests for ${{ inputs.browser }}"
        echo "================================="

        # Common parameters
        COMMON_PARAMS="\
        -Dcucumber.filter.tags=${{ inputs.scenarioTag }} \
        -Dbrowser=${{ inputs.browser }} \
        -DbaseUrl=${{ inputs.baseUrl }} \
        -DexplicitWait=${{ inputs.explicitWait }} \
        -Dthreads=${{ inputs.threads }}"

        # Gradle flags optimized for CI logs
        GRADLE_FLAGS="--no-daemon --console=plain --warning-mode summary"

        echo "Running tests..."

        ./gradlew executeFeatures \
            $GRADLE_FLAGS \
            $COMMON_PARAMS

        STATUS=$?

        if [ "$STATUS" -ne 0 ]; then
            echo "================================="
            echo "Tests failed. Re-running failed scenarios..."
            echo "================================="

            ./gradlew reExecuteFeatures \
                $GRADLE_FLAGS \
                $COMMON_PARAMS
        else
            echo "All tests passed. No retry needed."
        fi

      shell: bash

    # Upload log file.
    - name: Upload log file
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ inputs.browser }}-${{ github.run_id }}
        path: build/logs
        retention-days: 5
        if-no-files-found: warn

    # Upload Allure results
    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-${{ inputs.browser }}-${{ github.run_id }}
        path: build/allure-results
        retention-days: 5
        if-no-files-found: warn
