name: 'Execute features'
description: 'Execute Cucumber features with optional re-run of failed scenarios'

# Inputs the action accepts.
inputs:
  browser:
    description: 'Browser to execute tests (CHROME_HEADLESS | FIREFOX_HEADLESS)'
    required: false
    default: 'CHROME_HEADLESS'

  scenarioTag:
    description: 'Scenario tag to execute (e.g. "@TC-00001")'
    required: true
    default: '@regression'

  baseUrl:
    description: 'Base URL (e.g. "https://www.amazon.com")'
    required: true
    default: 'https://www.amazon.com'

  explicitWait:
    description: 'Explicit wait timeout in seconds (e.g. "30")'
    required: true
    default: '30'

  threads:
    description: 'Number of parallel threads (e.g. "4")'
    required: false
    default: '4'

runs:
  using: 'composite'

  steps:
    - name: Execute Features
      id: execute-features
      # Configuration variables in your repository.
      # Settings -> Secrets and variables -> Actions -> Secrets(secrets) or Variables(vars).
      run: |
        ./gradlew executeFeatures \
            -Dcucumber.filter.tags="${{ inputs.scenarioTag }}" \
            -Dbrowser="${{ inputs.browser }}" \
            -DbaseUrl="${{ inputs.baseUrl }}" \
            -DexplicitWait="${{ inputs.explicitWait }}" \
            -Dthreads="${{ inputs.threads }}"
      shell: bash

    # Re-execute if there are failed scenarios using the 'rerun.txt' file.
    - name: Re-Execute Failed Features
      # Composite actions, now support if conditionals.
      # https://github.blog/changelog/2021-11-09-github-actions-conditional-execution-of-steps-in-actions/
      if: ${{ failure() && steps.execute-features.conclusion == 'failure' }}
      run: |
        ./gradlew reExecuteFeatures \
            -Dbrowser="${{ inputs.browser }}" \
            -DbaseUrl="${{ inputs.baseUrl }}" \
            -DexplicitWait="${{ inputs.explicitWait }}" \
            -Dthreads="${{ inputs.threads }}"
      shell: bash

    # Upload log file.
    - name: Upload log file
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ inputs.browser }}-${{ github.run_id }}
        path: build/logs
        retention-days: 5
        if-no-files-found: warn

    # Upload Allure results
    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-${{ inputs.browser }}-${{ github.run_id }}
        path: build/allure-results
        retention-days: 5
        if-no-files-found: warn
